# Find libdataheap
if (LIBDATAHEAP_LIBRARIES AND LIBDATAHEAP_INCLUDE_DIRS)
  set (LibDataheap_FIND_QUIETLY TRUE)
endif (LIBDATAHEAP_LIBRARIES AND LIBDATAHEAP_INCLUDE_DIRS)

find_path(LIBDATAHEAP_INCLUDE_DIRS NAMES dataheap.h)
find_library(LIBDATAHEAP_LIBRARIES NAMES dataheap)

include (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibDataheap DEFAULT_MSG
  LIBDATAHEAP_LIBRARIES
  LIBDATAHEAP_INCLUDE_DIRS)

mark_as_advanced(LIBDATAHEAP_INCLUDE_DIRS LIBDATAHEAP_LIBRARIES) 
